---
- name: dhclient | generate the /etc/hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: dhclient | update the /etc/dhcp/dhclient.conf file
  template:
    src: dhclient.conf.j2
    dest: /etc/dhcp/dhclient.conf
    owner: root
    group: root
    mode: 0644
  with_items: "{{ dhclient_interfaces }}"
  register: dhclient_config

- name: dhclient | restart networking service
  service:
    name: networking
    state: restarted
  register: dhclient_networking
  when: dhclient_config.changed

- name: dhclient | updating the inventory with ansible_hostname={{ dhclient_host_name }}
  set_fact:
    ansible_hostname: "{{ dhclient_host_name }}"

- name: dhclient | updating the inventory with ansible_fqdn={{ dhclient_host_name }}.{{ dhclient_domain_name }}
  set_fact:
    ansible_fqdn: "{{ dhclient_host_name }}.{{ dhclient_domain_name }}"
